image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE

stages:
  - build

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u "$CI_REGISTRY_USER" --password-stdin

# build for tag
build_tag:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE_NAME:latest -t $DOCKER_IMAGE_NAME:$CI_COMMIT_TAG .
    - docker push $DOCKER_IMAGE_NAME:latest
    - docker push $DOCKER_IMAGE_NAME:$CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG  # 仅在检测到 Tag 时运行
      changes:
        - scripts/**
        - scripts/**/*
        - Dockerfile

# build for nightly
build_branch:
  stage: build
  script:
    - VERSION="nightly"
    - docker build -t $DOCKER_IMAGE_NAME:$VERSION .
    - docker push $DOCKER_IMAGE_NAME:$VERSION
  rules:
    - if: $CI_COMMIT_BRANCH  # 仅在分支构建时运行
      changes:
        - scripts/**
        - scripts/**/*
        - Dockerfile

build_dev:
  stage: build
  script:
    - VERSION="dev"
    - docker build -t $DOCKER_IMAGE_NAME:$VERSION .
    - docker push $DOCKER_IMAGE_NAME:$VERSION
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"  # 仅在 dev 分支构建时运行
      changes:
        - scripts/**
        - scripts/**/*
        - Dockerfile